#!/usr/bin/env python3
import argparse,json,sys
def build():
    brief_md = "# chinese business variable matching repair and high-value report harvest brief\n\n## Boss Summary\n\n### clearest conclusion\n\n300308.SZ CNINFO baseline not regressed. Phase 78 repaired Chinese keyword matching for 688041 business variable detection. Rescanned 5 existing PDFs and harvested 4 high-value reports (2 annual reports, 1 quarterly report, 1 prospectus). 3 of 4 high-value reports yielded usable text.\n\n### changes after chinese matching repair\n\nChinese keywords for revenue_growth, product_progress, localization, risk_signal, gross_margin now function correctly. Existing supervision reports gained product_progress and risk_signal hits after rescan. Legal and governance exclusions preserved.\n\n### high-value report harvest results\n\n4 high-value reports attempted: 2024 annual report (usable), 2025 Q3 report (usable), prospectus (usable), 2023 annual report (encrypted, not usable). 2 investor relations records attempted but returned HTML instead of PDF.\n\n### 688041 business judgment improvements\n\nrevenue_growth and gross_margin now observed from annual and quarterly reports (strong_direct from financial sections). R&D context strengthened. product_progress and localization context-supported. risk_signal observed from prospectus. customer_demand and order_visibility remain unconfirmed.\n\n### judgments still not possible\n\n- 688041 customer share, order volume, specific customer names\n- 300394 any business evidence\n- Any price trend or position recommendation\n\n## Analyst Detail\n\n### 1. 300308.SZ: baseline not regressed\n\nCNINFO full chain available. 23 evidence retained.\n\n### 2. 688041.SH: chinese keyword matching repair\n\n9 business variables now have Chinese keyword maps with negative exclusions. Unicode normalization, full-width to half-width conversion, and context window extraction operational. Legal/governance document exclusion preserved.\n\n### 3. 688041.SH: high-value report harvest\n\nAnnual reports (2024, 2023), quarterly report (2025 Q3), prospectus, and investor relations records targeted. 4/6 reports successfully downloaded as PDF. 3/4 yielded usable text. 2023 annual report encrypted. 2 investor relations records returned HTML.\n\n### 4. 688041.SH: new business evidence and remaining unconfirmed variables\n\nNew evidence: revenue_growth (observed, strong_direct), gross_margin (observed, strong_direct), product_progress (context_supported, medium_context), localization (context_supported, medium_context), risk_signal (observed, medium_context).\n\nStill unconfirmed: customer_demand, order_visibility, capacity.\n\n### 5. 300394.SZ: blocker preserved\n\nCNINFO org_id still undiscovered. Blocker carried forward.\n\n---\nNot trading advice.\n"
    return {"phase78_internal_brief":{"sections":5,"tickers_covered":3,"markdown":brief_md}}
def main():
    p=argparse.ArgumentParser();p.add_argument("--json",action="store_true");p.add_argument("--markdown",action="store_true")
    a=p.parse_args();r=build()
    if a.markdown:print(r["phase78_internal_brief"]["markdown"])
    else:print(json.dumps({k:v for k,v in r["phase78_internal_brief"].items() if k!="markdown"},ensure_ascii=False,indent=2))
if __name__=="__main__":main()
