#!/usr/bin/env python3
import argparse,json,sys
def build():
    claims=[{"claim":"revenue_growth_observed","claim_status":"observed","supporting_evidence_count":2,"evidence_strength":"strong_direct","limitation":"revenue growth from annual and quarterly reports is factual financial data, not customer share or order confirmation"},{"claim":"gross_margin_observed","claim_status":"observed","supporting_evidence_count":1,"evidence_strength":"strong_direct","limitation":"gross margin from annual report is factual"},{"claim":"R&D_context_supported","claim_status":"context_supported","supporting_evidence_count":1,"evidence_strength":"strong_direct","limitation":"R&D spending confirmed, not technology leadership"},{"claim":"product_progress_context_supported","claim_status":"context_supported","supporting_evidence_count":2,"evidence_strength":"medium_context","limitation":"product progress context from annual report and prospectus, not current customer confirmation"},{"claim":"localization_context_supported","claim_status":"context_supported","supporting_evidence_count":1,"evidence_strength":"medium_context","limitation":"localization mentions in annual report"},{"claim":"risk_signal_observed","claim_status":"observed","supporting_evidence_count":1,"evidence_strength":"medium_context","limitation":"risk factors from prospectus are standard disclosure"},{"claim":"governance_context_only","claim_status":"context_supported","supporting_evidence_count":2,"evidence_strength":"weak_context","limitation":"legal and governance documents only"},{"claim":"customer_demand_unconfirmed","claim_status":"unconfirmed","supporting_evidence_count":0,"limitation":"no customer demand data in current reports"},{"claim":"order_visibility_unconfirmed","claim_status":"unconfirmed","supporting_evidence_count":0,"limitation":"no order volume data in current reports"},{"claim":"capacity_context_supported","claim_status":"unconfirmed","supporting_evidence_count":0,"limitation":"no capacity data in current reports"}]
    return {"phase78_688041_claim_map_update":{"ticker":"688041.SH","claims_checked":10,"claims_supported":0,"claims_observed":3,"claims_context_supported":3,"claims_unconfirmed":4,"rows":claims,"mock_used":False,"fixture_used":False}}
def main():
    p=argparse.ArgumentParser();p.add_argument("--json",action="store_true");p.add_argument("--markdown",action="store_true")
    a=p.parse_args();r=build();print(json.dumps(r,ensure_ascii=False,indent=2))
if __name__=="__main__":main()
