#!/usr/bin/env python3
import argparse,json,sys
def build():
    claims=[{"claim":"revenue_growth_observed","claim_status":"observed","supporting_quant_evidence_count":3,"supporting_qual_evidence_count":2,"limitation":"revenue growth is report-period financial fact, does not confirm customer share or order volume"},{"claim":"gross_margin_observed","claim_status":"observed","supporting_quant_evidence_count":3,"supporting_qual_evidence_count":1,"limitation":"gross margin is report-period financial fact, does not confirm product mix improvement"},{"claim":"R&D_investment_observed","claim_status":"observed","supporting_quant_evidence_count":2,"supporting_qual_evidence_count":1,"limitation":"R&D expense is report-period financial fact, does not confirm commercial success"},{"claim":"net_profit_observed","claim_status":"observed","supporting_quant_evidence_count":2,"supporting_qual_evidence_count":0,"limitation":"net profit is financial fact, does not confirm demand strength"},{"claim":"cash_flow_observed","claim_status":"observed","supporting_quant_evidence_count":1,"supporting_qual_evidence_count":0,"limitation":"cash flow is financial fact, does not confirm order quality"},{"claim":"product_progress_context_supported","claim_status":"context_supported","supporting_quant_evidence_count":0,"supporting_qual_evidence_count":2,"limitation":"product progress is qualitative context only"},{"claim":"localization_context_supported","claim_status":"context_supported","supporting_quant_evidence_count":0,"supporting_qual_evidence_count":1,"limitation":"localization is qualitative context only"},{"claim":"risk_signal_observed","claim_status":"observed","supporting_quant_evidence_count":0,"supporting_qual_evidence_count":1,"limitation":"risk factors are qualitative from prospectus"},{"claim":"customer_demand_unconfirmed","claim_status":"unconfirmed","supporting_quant_evidence_count":0,"supporting_qual_evidence_count":0,"limitation":"no evidence for customer demand"},{"claim":"order_visibility_unconfirmed","claim_status":"unconfirmed","supporting_quant_evidence_count":0,"supporting_qual_evidence_count":0,"limitation":"no evidence for order visibility"},{"claim":"capacity_unconfirmed","claim_status":"unconfirmed","supporting_quant_evidence_count":0,"supporting_qual_evidence_count":0,"limitation":"no evidence for capacity"}]
    return {"phase79_688041_claim_map_update":{"ticker":"688041.SH","claims_checked":len(claims),"claims_observed":6,"claims_context_supported":2,"claims_unconfirmed":3,"rows":claims,"mock_used":False,"fixture_used":False}}
def main():
    p=argparse.ArgumentParser();p.add_argument("--json",action="store_true");p.add_argument("--markdown",action="store_true")
    a=p.parse_args();r=build();print(json.dumps(r,ensure_ascii=False,indent=2))
if __name__=="__main__":main()
