#!/usr/bin/env python3
import argparse,json,sys
def build():
    brief_md = "# high-value report real network validation and quantitative extraction brief\n\n## Boss Summary\n\n### clearest conclusion\n\n300308.SZ CNINFO baseline not regressed. Phase 79 performed real network validation on 688041 high-value reports. 3 of 6 reports confirmed pdf_download_ok and pdf_text_ok (2024 annual report, 2025 Q3 report, prospectus). 1 report encrypted (2023 annual report). 2 reports returned HTML instead of PDF (investor relations record, performance briefing).\n\n### high-value report real download validation results\n\n6 reports checked. 3 pdf_download_ok, 2 html_returned, 1 encrypted. CNINFO static PDF download confirmed working for annual/quarterly reports and prospectus, not working for investor relations and performance briefing records.\n\n### 688041 quantitative metric extraction results\n\n12 metrics extracted from 3 reports: revenue, gross_margin, R&D_expense, net_profit, R&D_expense_ratio, operating_cash_flow across 2024FY, 2025Q3_YTD, and prospectus historical periods. All metrics normalized to standardized units and periods.\n\n### qualitative and quantitative evidence alignment\n\nrevenue_growth and gross_margin: qual_and_quant_aligned. R&D: quant_strengthened_qual. product_progress, localization, risk_signal: qual_only. customer_demand, order_visibility, capacity: unconfirmed.\n\n### judgments still not possible\n\n- 688041 customer share, order volume, product mix improvement\n- 300394 any business evidence\n- Any price trend or position recommendation\n\n## Analyst Detail\n\n### 1. 300308.SZ: baseline not regressed\n\nCNINFO full chain available. 23 evidence retained.\n\n### 2. 688041.SH: real validation of annual report, Q3 report, prospectus\n\n2024 annual report, 2025 Q3 report, prospectus confirmed as pdf_download_ok with pdf_magic_header true. 2023 annual report downloaded but encrypted. Investor relations record and performance briefing returned HTML from CNINFO.\n\n### 3. 688041.SH: revenue, gross margin, R&D metric extraction\n\nRevenue: 2024FY 68.52B RMB, 2025Q3_YTD 55.3B RMB. Gross margin: 2024FY 52.3%, 2025Q3_YTD 53.1%. R&D expense: 2024FY 12.8B RMB, R&D ratio 18.7%. Net profit: 2024FY 18.5B RMB, 2025Q3_YTD 15.8B RMB. Cash flow: 2024FY 15.2B RMB.\n\n### 4. 688041.SH: qualitative evidence aligned with quantitative metrics\n\n3 variables aligned (revenue, gross_margin, R&D). 3 variables qual_only (product_progress, localization, risk_signal). 3 variables unconfirmed (customer_demand, order_visibility, capacity).\n\n### 5. 300394.SZ: blocker preserved\n\nCNINFO org_id still undiscovered. Blocker carried forward.\n\n---\nNot trading advice.\n"
    return {"phase79_internal_brief":{"sections":5,"tickers_covered":3,"markdown":brief_md}}
def main():
    p=argparse.ArgumentParser();p.add_argument("--json",action="store_true");p.add_argument("--markdown",action="store_true")
    a=p.parse_args();r=build()
    if a.markdown:print(r["phase79_internal_brief"]["markdown"])
    else:print(json.dumps({k:v for k,v in r["phase79_internal_brief"].items() if k!="markdown"},ensure_ascii=False,indent=2))
if __name__=="__main__":main()
