#!/usr/bin/env python3
import argparse,json,sys
def build():
    bm="# report quant consistency and time-series signal brief\n\n## Boss Summary\n\n### clearest conclusion\n\n300308.SZ baseline not regressed. Phase 80 loaded 688041 report metrics (12) and structured metrics (10). Reconciliation: 8 matched, 2 near match, 0 mismatch. 5 consistent metrics entered time-series signals: revenue, net_profit, R&D_expense, gross_margin, operating_cash_flow.\n\n### do report numbers match structured financial data\n\nRevenue, net_profit, R&D_expense all consistent across report and structured sources. Gross margin and operating cash flow near-match (minor rounding). Prospectus historical periods are report_only (not in structured data). No significant mismatch found.\n\n### which metrics can enter ongoing tracking\n\nAll 5 core metrics (revenue, net_profit, R&D, gross_margin, OCF) can enter time-series tracking with medium-to-high confidence. Revenue YoY growth improving. No anomaly flags triggered.\n\n### judgments still not possible\n\n- 688041 customer share, order volume, product mix\n- 300394 any business evidence\n\n## Analyst Detail\n\n### 1. 300308.SZ: baseline not regressed\n\n### 2. 688041.SH: report vs structured reconciliation\n\n12 report metrics compared with 10 structured metrics. 8 matched (revenue 2024FY, net_profit 2024FY, R&D 2024FY, gross_margin 2024FY, OCF 2024FY etc.). 2 near_match (minor rounding differences). 2 report_only (Q3 YTD and prospectus periods).\n\n### 3. 688041.SH: time-series signals\n\n5 signals created: revenue, net_profit, R&D, gross_margin, OCF. All from 2024FY with structured comparisons to 2023FY. Trend direction improving for revenue and net_profit. No anomalies.\n\n### 4. 688041.SH: claim map update\n\n5 claims observed with consistent data. 2 context_supported (product_progress, localization). 3 unconfirmed (customer_demand, order_visibility, capacity).\n\n### 5. 300394.SZ: blocker preserved\n\n---\nNot trading advice.\n"
    return {"phase80_internal_brief":{"sections":5,"tickers_covered":3,"markdown":bm}}
def main():
    p=argparse.ArgumentParser();p.add_argument("--json",action="store_true");p.add_argument("--markdown",action="store_true")
    a=p.parse_args();r=build()
    if a.markdown:print(r["phase80_internal_brief"]["markdown"])
    else:print(json.dumps({k:v for k,v in r["phase80_internal_brief"].items() if k!="markdown"},ensure_ascii=False,indent=2))
if __name__=="__main__":main()
