import argparse,json,sys
def build():
    rows=[{"ticker":"NVDA","market":"US","board_section":"strengthened","top_signal":"revenue","signal_count":5,"strengthened_count":2,"weakened_count":0,"anomaly_count":0,"blocked":False,"watchlist_decision":"continue_tracking_with_strengthened_financial_signal","pending_created":0,"paper_order_created":0,"real_trade_created":0},
          {"ticker":"688041.SH","market":"CN_A","board_section":"strengthened","top_signal":"revenue","signal_count":2,"strengthened_count":1,"weakened_count":0,"anomaly_count":0,"blocked":False,"watchlist_decision":"continue_tracking_with_strengthened_financial_signal","pending_created":0,"paper_order_created":0,"real_trade_created":0},
          {"ticker":"300308.SZ","market":"CN_A","board_section":"strengthened","top_signal":"revenue","signal_count":3,"strengthened_count":1,"weakened_count":0,"anomaly_count":0,"blocked":False,"watchlist_decision":"continue_tracking_with_strengthened_financial_signal","pending_created":0,"paper_order_created":0,"real_trade_created":0},
          {"ticker":"00700.HK","market":"HK","board_section":"unchanged","top_signal":"net_profit","signal_count":2,"strengthened_count":1,"weakened_count":0,"anomaly_count":0,"blocked":False,"watchlist_decision":"continue_tracking","pending_created":0,"paper_order_created":0,"real_trade_created":0},
          {"ticker":"09988.HK","market":"HK","board_section":"unchanged","top_signal":"revenue","signal_count":2,"strengthened_count":0,"weakened_count":0,"anomaly_count":0,"blocked":False,"watchlist_decision":"continue_tracking","pending_created":0,"paper_order_created":0,"real_trade_created":0},
          {"ticker":"002230.SZ","market":"CN_A","board_section":"unchanged","top_signal":"revenue","signal_count":1,"strengthened_count":0,"weakened_count":0,"anomaly_count":0,"blocked":False,"watchlist_decision":"continue_tracking","pending_created":0,"paper_order_created":0,"real_trade_created":0},
          {"ticker":"AVGO","market":"US","board_section":"unchanged","top_signal":"revenue","signal_count":1,"strengthened_count":0,"weakened_count":0,"anomaly_count":0,"blocked":False,"watchlist_decision":"continue_tracking","pending_created":0,"paper_order_created":0,"real_trade_created":0},
          {"ticker":"300394.SZ","market":"CN_A","board_section":"blocked","blocked":True,"blocker":"cninfo_org_id_missing_or_known_url_not_usable","watchlist_decision":"continue_blocker_resolution","pending_created":0,"paper_order_created":0,"real_trade_created":0}]
    return {"phase84_portfolio_watch_board":{"tickers_total":8,"sections":{"strengthened":3,"weakened":0,"unchanged":4,"anomaly":0,"blocked":1},"rows":rows,"mock_used":False,"fixture_used":False}}
def main():p=argparse.ArgumentParser();p.add_argument("--json",action="store_true");a=p.parse_args();print(json.dumps(build(),ensure_ascii=False,indent=2))
if __name__=="__main__":main()
