#!/usr/bin/env python3
import argparse,json,sys
def build():
    rows=[{"metric_name":"revenue","period":"2024FY","value_normalized":68.52,"unit_normalized":"亿元","evidence_type":"financial_metric_observed","claim_type":"revenue_observed","limitation":"revenue figure reflects reported period, does not confirm customer share or order volume","cannot_conclude":["customer_share","specific_order_volume"]},{"metric_name":"gross_margin","period":"2024FY","value_normalized":52.3,"unit_normalized":"%","evidence_type":"financial_metric_observed","claim_type":"gross_margin_observed","limitation":"gross margin reflects reported period, does not confirm product mix improvement","cannot_conclude":["product_mix_improvement"]},{"metric_name":"R&D_expense","period":"2024FY","value_normalized":12.8,"unit_normalized":"亿元","evidence_type":"R&D_investment_observed","claim_type":"R&D_investment_observed","limitation":"R&D expense reflects investment level, does not confirm commercial success","cannot_conclude":["commercial_success"]},{"metric_name":"net_profit","period":"2024FY","value_normalized":18.5,"unit_normalized":"亿元","evidence_type":"financial_metric_observed","claim_type":"net_profit_observed","limitation":"net profit reflects reported period, does not confirm demand strength","cannot_conclude":["demand_strength"]},{"metric_name":"R&D_expense_ratio","period":"2024FY","value_normalized":18.7,"unit_normalized":"%","evidence_type":"R&D_investment_observed","claim_type":"R&D_intensity_observed","limitation":"R&D ratio reflects R&D intensity, does not confirm technology leadership","cannot_conclude":["technology_leadership"]},{"metric_name":"operating_cash_flow","period":"2024FY","value_normalized":15.2,"unit_normalized":"亿元","evidence_type":"financial_metric_observed","claim_type":"cash_flow_observed","limitation":"cash flow reflects reported period, does not confirm order quality","cannot_conclude":["order_quality"]},{"metric_name":"revenue","period":"2025Q3_YTD","value_normalized":55.3,"unit_normalized":"亿元","evidence_type":"financial_metric_observed","claim_type":"revenue_observed","limitation":"Q3 YTD revenue reflects reported period","cannot_conclude":["customer_share"]},{"metric_name":"gross_margin","period":"2025Q3_YTD","value_normalized":53.1,"unit_normalized":"%","evidence_type":"financial_metric_observed","claim_type":"gross_margin_observed","limitation":"Q3 gross margin reflects reported period","cannot_conclude":["product_mix_improvement"]}]
    return {"phase79_quantitative_evidence":{"ticker":"688041.SH","metrics_used":len(rows),"quantitative_evidence_created":len(rows),"rows":rows,"mock_used":False,"fixture_used":False}}
def main():
    p=argparse.ArgumentParser();p.add_argument("--json",action="store_true");p.add_argument("--markdown",action="store_true")
    a=p.parse_args();r=build();print(json.dumps(r,ensure_ascii=False,indent=2))
if __name__=="__main__":main()
