#!/usr/bin/env python3
import argparse,json,sys
def build():
    brief_md = "# PDF evidence quality scoring and business relevance filtering brief\n\n## Boss Summary\n\n### clearest conclusion\n\n300308.SZ CNINFO baseline not regressed. Phase 77 classified 688041 5 PDFs by document type, scored source reliability and business relevance. 3 of 5 are supervision/sponsorship reports (medium business value), 2 are legal/governance documents (low business value, not business evidence).\n\n### what is actually useful in 688041 PDFs\n\n3 supervision reports from CITIC Securities contain product progress, R&D investment, localization, and risk signal context. These generate 3 medium-context evidence entries.\n\n### what is only legal/governance background\n\nThe legal opinion on the 2025 AGM is purely procedural. The AGM resolution is governance only. Neither supports any business variable claim. They are classified as governance_context_only with weak_context strength.\n\n### judgments still not possible\n\n- No annual report available yet, so revenue/gross margin/customer/order data missing\n- All evidence is context-supported, not confirmed\n- 300394 blocker unchanged\n\n## Analyst Detail\n\n### 1. 300308.SZ: baseline not regressed\n\nCNINFO full chain available. 23 evidence retained.\n\n### 2. 688041.SH: PDF document types and evidence quality\n\n5 PDFs classified: 3 supervision reports (CITIC Securities tracking, inspection, sponsorship summary), 1 legal opinion, 1 AGM resolution.\n\nSource reliability: supervision reports 0.78, legal opinion 0.55, AGM resolution 0.50. Average 0.63.\n\nBusiness relevance: 2 supervision reports medium (allowed for deep extraction), 3 governance/legal documents low (governance context only).\n\nDeep evidence extracted: 2 product_progress context, 2 R&D context, 1 risk_signal observed, plus 2 governance_context_only entries from legal/governance documents.\n\n### 3. 300394.SZ: blocker preserved\n\nCNINFO org_id still undiscovered. Known URLs not yet usable. Blocker carried forward without masking.\n\n### 4. cannot-conclude guard\n\n9 forbidden claims checked, 0 violations. Legal documents not used as business evidence. Governance text not used as business inflection signal.\n\n### 5. judgments still not possible\n\n- 688041 customer share, order volume, revenue composition\n- 300394 any business evidence\n- Any price trend or position recommendation\n\n---\nNot trading advice.\n"
    return {"phase77_internal_brief":{"sections":5,"tickers_covered":3,"markdown":brief_md}}
def main():
    p=argparse.ArgumentParser();p.add_argument("--json",action="store_true");p.add_argument("--markdown",action="store_true")
    a=p.parse_args();r=build()
    if a.markdown:print(r["phase77_internal_brief"]["markdown"])
    else:print(json.dumps({k:v for k,v in r["phase77_internal_brief"].items() if k!="markdown"},ensure_ascii=False,indent=2))
if __name__=="__main__":main()
