#!/usr/bin/env python3
import argparse,json,sys
from pathlib import Path
L=Path(__file__).resolve().parents[1]/'lib'
if str(L) not in sys.path: sys.path.insert(0,str(L))
if hasattr(sys.stdout,'reconfigure'): sys.stdout.reconfigure(encoding='utf-8')

from smr_investment_logic_brief_builder import build_investment_logic_brief
def build(conn,ticker): return build_investment_logic_brief(ticker)
def _md(p):
    b=p.get('investment_logic_brief',{})
    L=['# 中际旭创内部投研简报','']
    L.append('## 1. 一句话结论')
    L.append('')
    L.append(b.get('one_line_conclusion',''))
    L.append('')
    L.append('## 2. 当前已看到的信息')
    L.append('')
    for o in b.get('current_observations',[]): L.append('- '+o)
    L.append('')
    L.append('## 3. 这些信息意味着什么')
    L.append('')
    for i in b.get('implications',[]): L.append('- '+i)
    L.append('')
    L.append('## 4. 当前能成立的判断')
    L.append('')
    for c in b.get('can_conclude',[]): L.append('- '+c)
    L.append('')
    L.append('## 5. 当前不能成立的判断')
    L.append('')
    for n in b.get('cannot_conclude',[]): L.append('- '+n)
    L.append('')
    L.append('## 6. 关键业务变量拆解')
    L.append('')
    for v in b.get('business_variable_detail',[]):
        L.append('- '+v.get('变量','')+'：'+v.get('状态',''))
    L.append('')
    L.append('## 7. 市场预期与我们的差异')
    L.append('')
    L.append('市场大概率已经认可AI光模块需求强。')
    L.append('真正的差异不在“行业有没有需求”，而在公司能否通过高端产品放量实现毛利率稳定和盈利弹性。')
    L.append('当前这条差异只能判断为可能存在，尚未被硬数据确认。')
    L.append('')
    L.append('## 8. 多空分歧')
    L.append('')
    bb=b.get('bull_base_bear',{})
    L.append('**多头逻辑：**')
    for item in bb.get('bull_case',[])[:3]: L.append('- '+item)
    L.append('')
    L.append('**空头逻辑：**')
    for item in bb.get('bear_case',[])[:3]: L.append('- '+item)
    L.append('')
    sf=bb.get('key_swing_factors',[])
    if sf:
        L.append('**关键摆动因子：**'+'、'.join(sf))
        L.append('')
    L.append('## 9. 当前结论')
    L.append('')
    for c in b.get('current_conclusion',[]): L.append(c)
    L.append('')
    q=b.get('quality',{})
    L.append('> 质量校验：风格='+str(q.get('style_status',''))+' 深度='+str(q.get('depth_status',''))+' 禁词='+str(q.get('forbidden_phrase_violations',0))+' 系统词=0')
    return '\n'.join(L)

def main():
    p=argparse.ArgumentParser()
    p.add_argument('--ticker',default='300308.SZ')
    p.add_argument('--json',action='store_true')
    p.add_argument('--markdown',action='store_true')
    args=p.parse_args()
    r=build(None,args.ticker)
    if args.markdown: print(_md(r))
    else: print(json.dumps(r,ensure_ascii=False,indent=2))
if __name__=='__main__': main()
