CREATE TABLE IF NOT EXISTS data_source_health (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    source_key TEXT NOT NULL,
    market TEXT,
    asset_type TEXT,
    data_type TEXT NOT NULL,
    last_success_at TEXT,
    last_data_timestamp TEXT,
    expected_update_frequency TEXT,
    freshness_status TEXT NOT NULL,
    stale_after_minutes INTEGER,
    blocking_level TEXT NOT NULL,
    staleness_reason TEXT,
    affected_modules_json TEXT NOT NULL DEFAULT '[]',
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(source_key, market, asset_type, data_type)
);

CREATE TABLE IF NOT EXISTS recommendation_reviews (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    recommendation_id TEXT NOT NULL,
    previous_status TEXT NOT NULL,
    new_status TEXT NOT NULL,
    reviewer TEXT,
    review_action TEXT,
    review_comment TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    metadata_json TEXT NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS decision_ledger (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    decision_id TEXT UNIQUE NOT NULL,
    recommendation_id TEXT NOT NULL,
    ticker TEXT,
    market TEXT,
    theme TEXT,
    action TEXT NOT NULL,
    status TEXT NOT NULL,
    decision_time TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reference_price REAL,
    currency TEXT,
    suggested_position_pct REAL,
    max_position_pct REAL,
    thesis_summary TEXT,
    evidence_ids_json TEXT NOT NULL DEFAULT '[]',
    bear_case_summary TEXT,
    kill_conditions_json TEXT NOT NULL DEFAULT '[]',
    risk_notes TEXT,
    data_health_snapshot_json TEXT NOT NULL DEFAULT '{}',
    evidence_check_snapshot_json TEXT NOT NULL DEFAULT '{}',
    lint_snapshot_json TEXT NOT NULL DEFAULT '{}',
    risk_snapshot_json TEXT NOT NULL DEFAULT '{}',
    human_review_status TEXT,
    reviewer TEXT,
    review_comment TEXT,
    outcome_status TEXT NOT NULL DEFAULT 'open',
    outcome_price_1d REAL,
    outcome_price_1w REAL,
    outcome_price_1m REAL,
    outcome_price_3m REAL,
    thesis_confirmed INTEGER,
    failure_reason TEXT,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS agent_runs (
    run_id TEXT PRIMARY KEY,
    agent_or_script TEXT NOT NULL,
    entity_type TEXT,
    entity_id TEXT,
    status TEXT NOT NULL,
    started_at TEXT,
    completed_at TEXT,
    data_health_snapshot_json TEXT NOT NULL DEFAULT '{}',
    freshness_gate_result_json TEXT NOT NULL DEFAULT '{}',
    evidence_check_result_json TEXT NOT NULL DEFAULT '{}',
    lint_result_json TEXT NOT NULL DEFAULT '{}',
    source_registry_snapshot_json TEXT NOT NULL DEFAULT '{}',
    output_status TEXT,
    block_reasons_json TEXT NOT NULL DEFAULT '[]',
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
