def build_execution_brief_md():
 lines=[]
 lines.append("# Deep Dive Execution Brief")
 lines.append("")
 lines.append("## Execution Summary")
 lines.append("- Tasks executed: 3")
 lines.append("- Evidence strengthened: 2 (688041, NVDA)")
 lines.append("- Evidence partially confirmed: 1 (300394)")
 lines.append("- Tasks closed: 1 (NVDA)")
 lines.append("- Tasks need follow-up: 2 (688041, 300394)")
 lines.append("")
 lines.append("## DD-135-001: 688041 Valuation Input [NEEDS FOLLOW-UP]")
 lines.append("- Financial data: confirmed stable")
 lines.append("- Valuation: derived metrics reviewed, peer data limited")
 lines.append("- Manual confirmation needed: valuation metrics are estimates")
 lines.append("- Owner action: Review derived valuation metrics")
 lines.append("")
 lines.append("## DD-136-002: NVDA Financial Quality [CLOSED]")
 lines.append("- Financial quality: confirmed - revenue growth, margin expansion, FCF robust")
 lines.append("- AI catalyst: active")
 lines.append("- Routine monitoring continues")
 lines.append("")
 lines.append("## DD-136-003: 300394 Source Quality [NEEDS FOLLOW-UP]")
 lines.append("- Eastmoney: usable alternative source")
 lines.append("- CNINFO: org_id still missing")
 lines.append("- Owner action: Decide cninfo resolution strategy")
 lines.append("")
 lines.append("---")
 lines.append("*Research-only execution. No trade recommendations.*")
 return "\n".join(lines)
