def build_candidate_profiles():
    candidates = [
        {"ticker": "TSM", "name": "Taiwan Semiconductor", "market": "US", "currency": "USD",
         "potential_thesis": "Global semiconductor foundry leader, AI chip manufacturing beneficiary",
         "source_status": "SEC filing available, EDGAR accessible",
         "financial_access": "Public filings accessible, quarterly reports available",
         "valuation_feasibility": "P/E, P/B, revenue multiples calculable from public data",
         "evidence_readiness": "Industry reports, earnings calls, supply chain data available",
         "key_risks": "Geopolitical (Taiwan Strait), customer concentration, cyclical semiconductor demand",
         "activation_priority": "high", "estimated_effort": "2-3 sessions"},
        {"ticker": "ASML", "name": "ASML Holding", "market": "US", "currency": "USD",
         "potential_thesis": "Monopoly in EUV lithography, critical bottleneck for advanced chip manufacturing",
         "source_status": "SEC filing available, company investor relations accessible",
         "financial_access": "Public filings accessible, annual/quarterly reports available",
         "valuation_feasibility": "Premium multiple justified by monopoly position; DCF feasible",
         "evidence_readiness": "Industry data on lithography demand, capex trends from chipmakers",
         "key_risks": "Export controls (China), cyclical equipment demand, single-product dependency",
         "activation_priority": "high", "estimated_effort": "2-3 sessions"},
        {"ticker": "SNOW", "name": "Snowflake", "market": "US", "currency": "USD",
         "potential_thesis": "Cloud data platform leader, consumption-based revenue model, AI/ML data pipeline beneficiary",
         "source_status": "SEC filing available, earnings transcripts accessible",
         "financial_access": "Public filings accessible, quarterly reports with RPO/remaining performance obligations",
         "valuation_feasibility": "High-growth SaaS metrics (NDR, RPO, consumption trends); revenue multiple based",
         "evidence_readiness": "Cloud adoption trends, data warehouse market reports, partner ecosystem data",
         "key_risks": "High valuation multiple, cloud competition (Databricks, hyperscalers), consumption sensitivity",
         "activation_priority": "medium", "estimated_effort": "3-4 sessions"},
        {"ticker": "MU", "name": "Micron Technology", "market": "US", "currency": "USD",
         "potential_thesis": "Memory cycle recovery, AI-driven HBM (High Bandwidth Memory) demand growth",
         "source_status": "SEC filing available, earnings calls with detailed market commentary",
         "financial_access": "Public filings accessible, quarterly reports with ASP/bit shipment data",
         "valuation_feasibility": "Cycle-dependent; P/B and trough-earnings frameworks applicable",
         "evidence_readiness": "DRAM/NAND pricing data, HBM market forecasts, data center capex trends",
         "key_risks": "Memory price cyclicality, China competition, capex intensity, geopolitical export controls",
         "activation_priority": "medium", "estimated_effort": "2-3 sessions"},
        {"ticker": "AMD", "name": "Advanced Micro Devices", "market": "US", "currency": "USD",
         "potential_thesis": "CPU/GPU dual-platform beneficiary, data center growth, competitive positioning vs NVDA/INTC",
         "source_status": "SEC filing available, earnings transcripts accessible",
         "financial_access": "Public filings accessible, segment reporting (Data Center, Client, Gaming, Embedded)",
         "valuation_feasibility": "Peer-relative to NVDA/INTC; segment sum-of-parts feasible",
         "evidence_readiness": "x86 market share data, data center GPU adoption, PC market trends",
         "key_risks": "Competition from NVDA in AI GPU, Intel in CPU, cyclical PC market, execution risk",
         "activation_priority": "high", "estimated_effort": "2-3 sessions"},
    ]
    return {"phase148_candidate_profiles": {"candidates": len(candidates), "profiles": candidates, "auto_add_to_watchlist": False, "mock_used": False, "fixture_used": False}}
