def build_brief_md():
 L=[]
 L.append("# Phase111-126 Mainline Closeout")
 L.append("")
 L.append("## Status: COMPLETE")
 L.append("- 16 phases deployed (111 through 126)")
 L.append("- 7/8 tickers covered (3 CN_A + 2 HK + 2 US)")
 L.append("- 300394.SZ: CNINFO blocker retained")
 L.append("- 688041.SH: valuation partial retained")
 L.append("")
 L.append("## Core Capabilities")
 L.append("- Opportunity discovery -> candidate board -> watchlist loop")
 L.append("- Catalyst/inflection detection + cross-source scoring")
 L.append("- Master daily runner + system health monitoring")
 L.append("- External data source registry (11 sources, 12 pending probe)")
 L.append("- Daily research brief v2 (observed-first, multi-source)")
 L.append("- Owner feedback memory + decision journal")
 L.append("- Outcome tracking + signal effectiveness review")
 L.append("")
 L.append("## Safety Boundaries (10 enforced)")
 L.append("- No trading, no target price, no position sizing")
 L.append("- No paper order/trade, no broker API")
 L.append("- No profit/loss tracking, no return metrics")
 L.append("- No mock/fixture, no raw/OCR/browser")
 L.append("- Research-only mode across all 16 phases")
 L.append("")
 L.append("## Next Steps")
 L.append("- Path A: Network source probe execution sprint")
 L.append("- Path B: 300394 CNINFO manual resolution attempt")
 L.append("- Path C: New system capability expansion")
 L.append("")
 L.append("*Mainline closeout complete. System operational. Research-only.*")
 import os as _os
 return _os.linesep.join(L)
