def build_brief_md():
 L=[]
 L.append("# Signal Effectiveness Review")
 L.append("")
 L.append("## Status")
 L.append("- Signal effectiveness review system operational")
 L.append("- Ready to evaluate research signal quality")
 L.append("- Phase 111-126 mainline final review capability")
 L.append("")
 L.append("## Signal Types Reviewed")
 L.append("- 8 signal types: opportunity radar, catalyst, cross-source evidence, risk alert, source update, feedback signal, watchlist status, brief section impact")
 L.append("")
 L.append("## Usefulness & Noise Assessment")
 L.append("- 5 usefulness ratings: helpful, possibly helpful, neutral, not enough data, not helpful")
 L.append("- 5 noise levels: low, medium, high, false positive candidate, insufficient sample")
 L.append("")
 L.append("## Blocked Tickers")
 L.append("- 300394.SZ: CNINFO org_id missing, no signal to review")
 L.append("- 688041.SH: valuation incomplete, partial signal only")
 L.append("")
 L.append("## Safety")
 L.append("- No trading signal evaluation")
 L.append("- No profit/loss or return assessment")
 L.append("- Research quality improvement only")
 L.append("")
 L.append("*No investment recommendations. Research signal quality review only.*")
 import os as _os
 return _os.linesep.join(L)
