def build_decision_brief_md():
 L=[]
 L.append('# Decision Journal')
 L.append('')
 L.append('## Status')
 L.append('- Decision journal system operational')
 L.append('- Ready to record research decisions')
 L.append('- All safety boundaries enforced')
 L.append('')
 L.append('## Decision Types')
 L.append('- 10 decision types covering watchlist, deep dive, signal override, source trust, opportunity, risk, research focus, gap, and manual override')
 L.append('')
 L.append('## Blocked Tickers')
 L.append('- 300394.SZ: CNINFO org_id missing, remains blocked')
 L.append('- 688041.SH: valuation incomplete')
 L.append('')
 L.append('## Safety')
 L.append('- Trade-related decisions are blocked')
 L.append('- Buy/sell/price/position terms rejected')
 L.append('- Research-only mode enforced')
 L.append('')
 L.append('*No investment recommendations. No trading signals.*')
 import os as _os
 return _os.linesep.join(L)