def build_discovery_sources():
    sources = [
        {"source_id": "theme_based", "name": "Theme-based Discovery", "method": "Scan existing thesis themes and identify peer/adjacent companies in same thematic", "example_triggers": ["AI GPU demand -> Broadcom, Marvell", "Cloud acceleration -> Snowflake, Datadog", "Semiconductor equipment -> ASML, AMAT, LRCX"]},
        {"source_id": "peer_based", "name": "Peer-based Discovery", "method": "For each covered ticker, identify direct competitors and market peers", "example_triggers": ["NVDA peers: AMD, INTC", "ASML peers: AMAT, LRCX, KLAC", "TSM peers: Samsung, Intel foundry"]},
        {"source_id": "industry_chain", "name": "Industry Chain Discovery", "method": "Trace upstream/downstream from covered tickers along value chain", "example_triggers": ["GPU -> HBM memory (MU, SK Hynix)", "Chip manufacturing -> equipment (AMAT, LRCX)", "Chip design -> EDA tools (SNPS, CDNS)"]},
        {"source_id": "news_event", "name": "News/Event Discovery", "method": "Monitor earnings surprises, product launches, regulatory changes for new ticker relevance", "example_triggers": ["CHIPS Act funding recipients", "New AI product announcements", "Export control updates affecting supply chain"]},
        {"source_id": "financial_change", "name": "Financial Change Discovery", "method": "Detect significant financial metric changes (revenue inflection, margin expansion, R&D ramp) in sector peers", "example_triggers": ["Revenue growth acceleration in semiconductor sector", "Gross margin expansion in software/SaaS", "R&D ratio increase suggesting new product cycle"]},
        {"source_id": "customer_capex", "name": "Customer/Capex Discovery", "method": "Track major customer capex announcements and supplier beneficiaries", "example_triggers": ["Hyperscaler capex -> NVIDIA, AMD, AVGO, MU", "TSMC capex -> ASML, AMAT, LRCX", "Enterprise AI spend -> SNOW, CRM, NOW"]},
        {"source_id": "product_roadmap", "name": "Product Roadmap Discovery", "method": "Identify companies with upcoming product cycles that may drive revenue inflection", "example_triggers": ["Next-gen GPU launch cycle", "New semiconductor node transition", "Enterprise software platform refresh"]},
        {"source_id": "supply_chain", "name": "Supply Chain Discovery", "method": "Identify critical suppliers and bottleneck components", "example_triggers": ["Advanced packaging suppliers", "Silicon carbide substrate suppliers", "Optical component suppliers"]},
        {"source_id": "external_public_lists", "name": "External Public Lists", "method": "Reference public sector indices, ETF holdings, analyst coverage lists", "example_triggers": ["SOX index constituents", "SMH ETF holdings", "AI-focused fund holdings"]},
    ]
    return {"phase151_discovery_sources": {"sources": len(sources), "source_list": sources, "mock_used": False, "fixture_used": False}}
