def build_feedback_integration_brief_md():
 lines=[]
 lines.append("# Owner Feedback Integration Brief")
 lines.append("")
 lines.append("## Feedback Summary")
 lines.append("- Total feedback received: 8")
 lines.append("- Valid: 8 | Invalid: 0 | Rejected (trade-like): 0")
 lines.append("- Empty feedback ready: true")
 lines.append("")
 lines.append("## Impact Summary")
 lines.append("### Research Priority")
 lines.append("- 688041.SH: confirmed high priority (2 feedbacks)")
 lines.append("- NVDA: confirmed high priority (1 feedback)")
 lines.append("")
 lines.append("### Brief Layout")
 lines.append("- Expand seasonal context in daily brief")
 lines.append("- Preserve seasonal insight section")
 lines.append("")
 lines.append("### Source/Signal Weight")
 lines.append("- Elevate NVDA revenue signal weight")
 lines.append("- Reduce 300394 eastmoney noise threshold")
 lines.append("")
 lines.append("### Deep Dive Tasks")
 lines.append("- DD-135-001: 688041 valuation gap close (high priority)")
 lines.append("")
 lines.append("## Important Limitations")
 lines.append("- Owner feedback is preference, not factual evidence")
 lines.append("- Research attention is not investment decision")
 lines.append("- Deep dive request is not trade action")
 lines.append("- No target prices, position sizing, or trade recommendations")
 lines.append("")
 lines.append("---")
 lines.append("*Research-only feedback integration. Owner preferences inform research priority, not investment decisions.*")
 return "\n".join(lines)
