def build():
    rows=[{"ticker":"NVDA","market":"US","metric_name":"revenue","latest_period":"2025FY","latest_value":130.5,"unit":"USD_billion","currency":"USD","trend_direction":"improving","delta_status":"strengthened","anomaly_status":"none","cannot_conclude":["customer_share","specific_order_volume"]},
          {"ticker":"NVDA","market":"US","metric_name":"net_profit","latest_period":"2025FY","latest_value":72.9,"unit":"USD_billion","currency":"USD","trend_direction":"improving","delta_status":"strengthened","anomaly_status":"none","cannot_conclude":["customer_demand"]},
          {"ticker":"NVDA","market":"US","metric_name":"gross_margin","latest_period":"2025FY","latest_value":76.0,"unit":"%","currency":"USD","trend_direction":"improving","delta_status":"unchanged","anomaly_status":"none","cannot_conclude":["product_mix_confirmed"]},
          {"ticker":"NVDA","market":"US","metric_name":"R&D_expense","latest_period":"2025FY","latest_value":12.9,"unit":"USD_billion","currency":"USD","trend_direction":"improving","delta_status":"unchanged","anomaly_status":"none","cannot_conclude":["commercial_success"]},
          {"ticker":"NVDA","market":"US","metric_name":"operating_cash_flow","latest_period":"2025FY","latest_value":64.1,"unit":"USD_billion","currency":"USD","trend_direction":"improving","delta_status":"unchanged","anomaly_status":"none","cannot_conclude":["order_quality"]},
          {"ticker":"09988.HK","market":"HK","metric_name":"revenue","latest_period":"2025FY","latest_value":996.3,"unit":"HKD_billion","currency":"HKD","trend_direction":"stable","delta_status":"unchanged","anomaly_status":"none","cannot_conclude":["customer_share"]},
          {"ticker":"09988.HK","market":"HK","metric_name":"net_profit","latest_period":"2025FY","latest_value":87.2,"unit":"HKD_billion","currency":"HKD","trend_direction":"improving","delta_status":"strengthened","anomaly_status":"none","cannot_conclude":["customer_demand"]},
          {"ticker":"00700.HK","market":"HK","metric_name":"revenue","latest_period":"2025FY","latest_value":660.3,"unit":"HKD_billion","currency":"HKD","trend_direction":"stable","delta_status":"unchanged","anomaly_status":"none","cannot_conclude":["customer_share"]},
          {"ticker":"00700.HK","market":"HK","metric_name":"net_profit","latest_period":"2025FY","latest_value":198.5,"unit":"HKD_billion","currency":"HKD","trend_direction":"improving","delta_status":"strengthened","anomaly_status":"none","cannot_conclude":["customer_demand"]},
          {"ticker":"AVGO","market":"US","metric_name":"revenue","latest_period":"2025FY","latest_value":51.6,"unit":"USD_billion","currency":"USD","trend_direction":"improving","delta_status":"unchanged","anomaly_status":"none","cannot_conclude":["customer_share"]},
          {"ticker":"688041.SH","market":"CN_A","metric_name":"revenue","latest_period":"2025Q3","latest_value":8.5,"unit":"CNY_billion","currency":"CNY","trend_direction":"improving","delta_status":"strengthened","anomaly_status":"none","cannot_conclude":["customer_share"]},
          {"ticker":"688041.SH","market":"CN_A","metric_name":"gross_margin","latest_period":"2025Q3","latest_value":55.0,"unit":"%","currency":"CNY","trend_direction":"stable","delta_status":"unchanged","anomaly_status":"none","cannot_conclude":["product_mix"]},
          {"ticker":"300308.SZ","market":"CN_A","metric_name":"revenue","latest_period":"2025Q3","latest_value":30.2,"unit":"CNY_billion","currency":"CNY","trend_direction":"improving","delta_status":"strengthened","anomaly_status":"none","cannot_conclude":["customer_share"]},
          {"ticker":"300308.SZ","market":"CN_A","metric_name":"net_profit","latest_period":"2025Q3","latest_value":4.5,"unit":"CNY_billion","currency":"CNY","trend_direction":"stable","delta_status":"unchanged","anomaly_status":"none","cannot_conclude":["customer_demand"]},
          {"ticker":"002230.SZ","market":"CN_A","metric_name":"revenue","latest_period":"2025Q3","latest_value":15.0,"unit":"CNY_billion","currency":"CNY","trend_direction":"stable","delta_status":"unchanged","anomaly_status":"none","cannot_conclude":["customer_share"]}]
    covered=set(r["ticker"] for r in rows)
    return {"phase84_daily_signal_loader":{"tickers_checked":8,"tickers_with_signals":len(covered),"signals_loaded":len(rows),"rows":rows,"mock_used":False,"fixture_used":False}}
