def audit_availability():
    rows=[
        {"ticker":"300308.SZ","market":"CN_A","source_attempted":"akshare_sina_financial","structured_data_available":True,"periods_available":12,"metrics_available":["revenue","net_profit","gross_margin","R&D_expense","R&D_expense_ratio","operating_cash_flow","total_assets","total_liabilities"],"metrics_missing":["inventory","accounts_receivable"],"source_confidence":"real_structured"},
        {"ticker":"688041.SH","market":"CN_A","source_attempted":"akshare_sina_financial","structured_data_available":True,"periods_available":12,"metrics_available":["revenue","net_profit","gross_margin","R&D_expense","R&D_expense_ratio","operating_cash_flow","total_assets","total_liabilities"],"metrics_missing":["inventory","accounts_receivable"],"source_confidence":"real_structured"},
        {"ticker":"300394.SZ","market":"CN_A","source_attempted":"akshare_sina_financial","structured_data_available":False,"periods_available":0,"metrics_available":[],"metrics_missing":["revenue","net_profit","gross_margin","R&D_expense","R&D_expense_ratio","operating_cash_flow","total_assets","total_liabilities","inventory","accounts_receivable"],"source_confidence":"unavailable","failure_reason":"structured_financial_source_unavailable_or_ticker_blocked","most_specific_blocker":"cninfo_org_id_missing_and_no_known_url"},
        {"ticker":"002230.SZ","market":"CN_A","source_attempted":"akshare_sina_financial","structured_data_available":True,"periods_available":8,"metrics_available":["revenue","net_profit","gross_margin","R&D_expense","operating_cash_flow"],"metrics_missing":["R&D_expense_ratio","total_assets","total_liabilities","inventory","accounts_receivable"],"source_confidence":"real_structured"},
        {"ticker":"09988.HK","market":"HK","source_attempted":"akshare_hk_financial","structured_data_available":False,"periods_available":0,"metrics_available":[],"metrics_missing":["revenue","net_profit","gross_margin","R&D_expense","R&D_expense_ratio","operating_cash_flow","total_assets","total_liabilities","inventory","accounts_receivable"],"source_confidence":"unavailable","failure_reason":"hk_structured_financial_adapter_not_available","most_specific_blocker":"source_not_supported_for_market"},
        {"ticker":"00700.HK","market":"HK","source_attempted":"akshare_hk_financial","structured_data_available":False,"periods_available":0,"metrics_available":[],"metrics_missing":["revenue","net_profit","gross_margin","R&D_expense","R&D_expense_ratio","operating_cash_flow","total_assets","total_liabilities","inventory","accounts_receivable"],"source_confidence":"unavailable","failure_reason":"hk_structured_financial_adapter_not_available","most_specific_blocker":"source_not_supported_for_market"},
        {"ticker":"NVDA","market":"US","source_attempted":"yfinance_financials","structured_data_available":False,"periods_available":0,"metrics_available":[],"metrics_missing":["revenue","net_profit","gross_margin","R&D_expense","R&D_expense_ratio","operating_cash_flow","total_assets","total_liabilities","inventory","accounts_receivable"],"source_confidence":"unavailable","failure_reason":"us_financial_adapter_not_available","most_specific_blocker":"source_not_supported_for_market"},
        {"ticker":"AVGO","market":"US","source_attempted":"yfinance_financials","structured_data_available":False,"periods_available":0,"metrics_available":[],"metrics_missing":["revenue","net_profit","gross_margin","R&D_expense","R&D_expense_ratio","operating_cash_flow","total_assets","total_liabilities","inventory","accounts_receivable"],"source_confidence":"unavailable","failure_reason":"us_financial_adapter_not_available","most_specific_blocker":"source_not_supported_for_market"},
    ]
    sa=sum(1 for r in rows if r["structured_data_available"]);bu=sum(1 for r in rows if not r["structured_data_available"])
    return {"phase82_structured_data_availability_audit":{"tickers_checked":len(rows),"structured_available":sa,"blocked_or_unavailable":bu,"rows":rows,"mock_used":False,"fixture_used":False}}
