import json,os
def build_approval_domain_registry():
    domains=[
        {"domain_id":"ha01","domain_name":"approval_policy","readiness_status":"ready","policy_defined":True,"schema_defined":True,"audit_supported":True,"simulation_supported":True,"blockers":[],"manual_actions":[],"allowed_next_action":"none"},
        {"domain_id":"ha02","domain_name":"approval_state_machine","readiness_status":"partial_ready","policy_defined":True,"schema_defined":True,"audit_supported":True,"simulation_supported":True,"blockers":[],"manual_actions":["configure_operator_roles"],"allowed_next_action":"define_operator_identities"},
        {"domain_id":"ha03","domain_name":"approval_request_schema","readiness_status":"ready","policy_defined":True,"schema_defined":True,"audit_supported":True,"simulation_supported":True,"blockers":[],"manual_actions":[],"allowed_next_action":"none"},
        {"domain_id":"ha04","domain_name":"approval_decision_schema","readiness_status":"ready","policy_defined":True,"schema_defined":True,"audit_supported":True,"simulation_supported":True,"blockers":[],"manual_actions":[],"allowed_next_action":"none"},
        {"domain_id":"ha05","domain_name":"two_step_approval","readiness_status":"partial_ready","policy_defined":True,"schema_defined":True,"audit_supported":False,"simulation_supported":True,"blockers":[],"manual_actions":["assign_second_approver"],"allowed_next_action":"set_up_dual_approver_list"},
        {"domain_id":"ha06","domain_name":"approval_expiration","readiness_status":"ready","policy_defined":True,"schema_defined":True,"audit_supported":True,"simulation_supported":True,"blockers":[],"manual_actions":[],"allowed_next_action":"none"},
        {"domain_id":"ha07","domain_name":"approval_revocation","readiness_status":"partial_ready","policy_defined":True,"schema_defined":True,"audit_supported":True,"simulation_supported":True,"blockers":[],"manual_actions":["define_revocation_audit_trail"],"allowed_next_action":"add_revocation_reason_field"},
        {"domain_id":"ha08","domain_name":"operator_identity","readiness_status":"not_ready","policy_defined":True,"schema_defined":False,"audit_supported":False,"simulation_supported":False,"blockers":["no_operator_identity_store","no_rbac_system"],"manual_actions":["provision_operator_ids","configure_roles"],"allowed_next_action":"create_operator_identity_registry"},
        {"domain_id":"ha09","domain_name":"approval_audit_log","readiness_status":"ready","policy_defined":True,"schema_defined":True,"audit_supported":True,"simulation_supported":True,"blockers":[],"manual_actions":[],"allowed_next_action":"none"},
        {"domain_id":"ha10","domain_name":"manual_override","readiness_status":"partial_ready","policy_defined":True,"schema_defined":True,"audit_supported":True,"simulation_supported":True,"blockers":[],"manual_actions":["require_supervisor_for_override"],"allowed_next_action":"add_override_justification_field"},
        {"domain_id":"ha11","domain_name":"no_order_approval_simulation","readiness_status":"ready","policy_defined":True,"schema_defined":True,"audit_supported":True,"simulation_supported":True,"blockers":[],"manual_actions":[],"allowed_next_action":"none"},
        {"domain_id":"ha12","domain_name":"approval_guardrail","readiness_status":"partial_ready","policy_defined":True,"schema_defined":True,"audit_supported":True,"simulation_supported":True,"blockers":[],"manual_actions":["define_guardrail_violation_severity"],"allowed_next_action":"add_guardrail_severity_levels"}
    ]
    return {"phase104_approval_domain_registry":{"total_domains":len(domains),"domains":domains,"mock_used":False,"fixture_used":False}}
