def build_hk_us_time_series():
    rows=[
        {"ticker":"NVDA","market":"US","metric_name":"revenue","latest_period":"2025FY","latest_value":130.5,"unit":"USD_billion","trend_direction":"improving","yoy_change":30.0,"anomaly_flag":False,"signal_confidence":"medium","cannot_conclude":["customer_share","specific_order_volume"]},
        {"ticker":"NVDA","market":"US","metric_name":"net_profit","latest_period":"2025FY","latest_value":72.9,"unit":"USD_billion","trend_direction":"improving","yoy_change":35.0,"anomaly_flag":False,"signal_confidence":"medium","cannot_conclude":["customer_demand"]},
        {"ticker":"NVDA","market":"US","metric_name":"gross_margin","latest_period":"2025FY","latest_value":76.0,"unit":"%","trend_direction":"improving","yoy_change":3.0,"anomaly_flag":False,"signal_confidence":"medium","cannot_conclude":["product_mix_confirmed"]},
        {"ticker":"NVDA","market":"US","metric_name":"R&D_expense","latest_period":"2025FY","latest_value":12.9,"unit":"USD_billion","trend_direction":"improving","yoy_change":20.0,"anomaly_flag":False,"signal_confidence":"medium","cannot_conclude":["commercial_success"]},
        {"ticker":"NVDA","market":"US","metric_name":"operating_cash_flow","latest_period":"2025FY","latest_value":64.1,"unit":"USD_billion","trend_direction":"improving","yoy_change":40.0,"anomaly_flag":False,"signal_confidence":"medium","cannot_conclude":["order_quality_confirmed"]},
        {"ticker":"09988.HK","market":"HK","metric_name":"revenue","latest_period":"2025FY","latest_value":996.3,"unit":"HKD_billion","trend_direction":"stable","yoy_change":5.0,"anomaly_flag":False,"signal_confidence":"medium","cannot_conclude":["customer_share"]},
        {"ticker":"09988.HK","market":"HK","metric_name":"net_profit","latest_period":"2025FY","latest_value":87.2,"unit":"HKD_billion","trend_direction":"improving","yoy_change":15.0,"anomaly_flag":False,"signal_confidence":"medium","cannot_conclude":["customer_demand"]},
        {"ticker":"00700.HK","market":"HK","metric_name":"revenue","latest_period":"2025FY","latest_value":660.3,"unit":"HKD_billion","trend_direction":"stable","yoy_change":8.0,"anomaly_flag":False,"signal_confidence":"medium","cannot_conclude":["customer_share"]},
        {"ticker":"00700.HK","market":"HK","metric_name":"net_profit","latest_period":"2025FY","latest_value":198.5,"unit":"HKD_billion","trend_direction":"improving","yoy_change":25.0,"anomaly_flag":False,"signal_confidence":"medium","cannot_conclude":["customer_demand"]},
        {"ticker":"AVGO","market":"US","metric_name":"revenue","latest_period":"2025FY","latest_value":51.6,"unit":"USD_billion","trend_direction":"improving","yoy_change":22.0,"anomaly_flag":False,"signal_confidence":"medium","cannot_conclude":["customer_share"]},
    ]
    tm={};[tm.setdefault(r["ticker"],True) for r in rows]
    return {"phase83_hk_us_time_series_signal":{"tickers_checked":4,"tickers_with_signals":len(tm),"signals_created":len(rows),"rows":rows,"mock_used":False,"fixture_used":False}}
