def build_official_source_identity_map():
 identity_map={
  "sec_edgar":{"official_name":"SEC EDGAR Full-Text Search","official_url":"https://www.sec.gov/cgi-bin/browse-edgar","agency":"U.S. Securities and Exchange Commission","market":"US","data_type":"filings","access_level":"free_no_key","primary_blocked":True,"reachable_from_cn":False},
  "sec_10k":{"official_name":"SEC 10-K Annual Report","official_url":"https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=NVDA&type=10-K","agency":"U.S. Securities and Exchange Commission","market":"US","data_type":"annual_report","access_level":"free_no_key","primary_blocked":True,"reachable_from_cn":False},
  "sec_10q":{"official_name":"SEC 10-Q Quarterly Report","official_url":"https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=NVDA&type=10-Q","agency":"U.S. Securities and Exchange Commission","market":"US","data_type":"quarterly_report","primary_blocked":True,"reachable_from_cn":False},
  "sec_8k":{"official_name":"SEC 8-K Current Report","official_url":"https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=NVDA&type=8-K","agency":"U.S. Securities and Exchange Commission","market":"US","data_type":"current_report","primary_blocked":True,"reachable_from_cn":False},
  "hkex_news":{"official_name":"HKEX News/Announcement RSS","official_url":"https://www.hkexnews.hk","agency":"Hong Kong Exchanges and Clearing","market":"HK","data_type":"news_announcement","primary_blocked":True,"reachable_from_cn":False},
  "hkex_filing":{"official_name":"HKEX Published Financial Filings","official_url":"https://www.hkexnews.hk/index.htm","agency":"Hong Kong Exchanges and Clearing","market":"HK","data_type":"filings","primary_blocked":True,"reachable_from_cn":False},
  "transcript_guidance_manual":{"official_name":"Earnings Call Transcript Aggregation","official_url":"N/A","agency":"Various (Seeking Alpha, Motley Fool, etc.)","market":"HK_US","data_type":"transcript_guidance","access_level":"manual_or_paid","primary_blocked":False,"reachable_from_cn":"manual_aggregation_required"}
 }
 return {"phase129_official_source_identity_map":{"total":len(identity_map),"sources":identity_map,"all_identified":True,"mock_used":False,"fixture_used":False}}
