from smr_phase88_config import get_directions,get_signal_types
def build_connector_registry():
    connectors=[{"connector_id":"eastmoney_news_connector","source_type":"public_news_api","market":"CN_A","industry_directions":["ai_optical_module","ai_chip_domestic_compute","cloud_capex_ai_infra","semiconductor_ai_infra_supply_chain"],"signal_types":["industry_news","product_price_supply_demand","policy_export_control_supply_chain_risk"],"execution_mode":"api_search","requires_network":True,"supports_api":True,"supports_rss":False,"supports_html":False,"supports_existing_pool":False,"supports_known_url":False,"raw_save_allowed":False,"login_required":False,"reliability_baseline":0.65,"fallback_priority":1,"known_limitations":"CN_A only; requires keyword search; rate-limited"},
    {"connector_id":"existing_pdf_text_pool_connector","source_type":"existing_text_pool","market":"CN_A","industry_directions":["ai_optical_module","ai_chip_domestic_compute","semiconductor_ai_infra_supply_chain"],"signal_types":["order_contract_tender","product_price_supply_demand","policy_export_control_supply_chain_risk"],"execution_mode":"text_search","requires_network":False,"supports_api":False,"supports_rss":False,"supports_html":False,"supports_existing_pool":True,"supports_known_url":False,"raw_save_allowed":False,"login_required":False,"reliability_baseline":0.85,"fallback_priority":2,"known_limitations":"Quarterly data; not real-time"},
    {"connector_id":"yfinance_news_connector","source_type":"public_news_api","market":"US_HK","industry_directions":["cloud_capex_ai_infra","semiconductor_ai_infra_supply_chain"],"signal_types":["industry_news","capex_demand_proxy"],"execution_mode":"api_ticker_news","requires_network":True,"supports_api":True,"supports_rss":False,"supports_html":False,"supports_existing_pool":False,"supports_known_url":False,"raw_save_allowed":False,"login_required":False,"reliability_baseline":0.60,"fallback_priority":1,"known_limitations":"English only; ticker-associated news"},
    {"connector_id":"cninfo_disclosure_connector","source_type":"disclosure_api","market":"CN_A","industry_directions":["ai_optical_module","ai_chip_domestic_compute"],"signal_types":["order_contract_tender","product_price_supply_demand"],"execution_mode":"api_disclosure_search","requires_network":True,"supports_api":True,"supports_rss":False,"supports_html":False,"supports_existing_pool":True,"supports_known_url":False,"raw_save_allowed":False,"login_required":False,"reliability_baseline":0.75,"fallback_priority":2,"known_limitations":"Requires valid cninfo org_id"},
    {"connector_id":"company_ir_known_url_connector","source_type":"known_url_catalog","market":"ALL","industry_directions":["ai_optical_module","ai_chip_domestic_compute","cloud_capex_ai_infra","semiconductor_ai_infra_supply_chain"],"signal_types":["industry_news","order_contract_tender","product_price_supply_demand"],"execution_mode":"url_fetch_text","requires_network":True,"supports_api":False,"supports_rss":False,"supports_html":True,"supports_existing_pool":False,"supports_known_url":True,"raw_save_allowed":False,"login_required":False,"reliability_baseline":0.50,"fallback_priority":3,"known_limitations":"Manual curation; URLs may change"},
    {"connector_id":"government_policy_connector","source_type":"public_policy_page","market":"CN_A_US","industry_directions":["ai_chip_domestic_compute","semiconductor_ai_infra_supply_chain"],"signal_types":["policy_export_control_supply_chain_risk"],"execution_mode":"url_fetch_text","requires_network":True,"supports_api":False,"supports_rss":False,"supports_html":True,"supports_existing_pool":False,"supports_known_url":True,"raw_save_allowed":False,"login_required":False,"reliability_baseline":0.70,"fallback_priority":3,"known_limitations":"Formal policy docs; interpretation caution required"},
    {"connector_id":"public_industry_rss_connector","source_type":"public_rss_feed","market":"US_HK","industry_directions":["cloud_capex_ai_infra","semiconductor_ai_infra_supply_chain"],"signal_types":["industry_news","capex_demand_proxy"],"execution_mode":"rss_fetch","requires_network":True,"supports_api":False,"supports_rss":True,"supports_html":False,"supports_existing_pool":False,"supports_known_url":False,"raw_save_allowed":False,"login_required":False,"reliability_baseline":0.55,"fallback_priority":3,"known_limitations":"Not ticker-specific; broad industry scope"},
    {"connector_id":"curated_keyword_connector","source_type":"static_keyword_catalog","market":"ALL","industry_directions":["ai_optical_module","ai_chip_domestic_compute","cloud_capex_ai_infra","semiconductor_ai_infra_supply_chain"],"signal_types":["industry_news","capex_demand_proxy"],"execution_mode":"static_lookup","requires_network":False,"supports_api":False,"supports_rss":False,"supports_html":False,"supports_existing_pool":False,"supports_known_url":False,"raw_save_allowed":False,"login_required":False,"reliability_baseline":0.55,"fallback_priority":4,"known_limitations":"Static; requires manual refresh"},
    {"connector_id":"exchange_announcement_connector","source_type":"exchange_announcement_api","market":"CN_A","industry_directions":["ai_optical_module","ai_chip_domestic_compute"],"signal_types":["order_contract_tender","product_price_supply_demand"],"execution_mode":"api_announcement_search","requires_network":True,"supports_api":True,"supports_rss":False,"supports_html":False,"supports_existing_pool":False,"supports_known_url":False,"raw_save_allowed":False,"login_required":False,"reliability_baseline":0.70,"fallback_priority":2,"known_limitations":"CN exchange only; keyword-based search"}]
    return {"phase88_connector_registry":{"connectors_defined":len(connectors),"api_connectors":sum(1 for c in connectors if c["supports_api"]),"rss_connectors":sum(1 for c in connectors if c["supports_rss"]),"html_connectors":sum(1 for c in connectors if c["supports_html"]),"pool_connectors":sum(1 for c in connectors if c["supports_existing_pool"]),"rows":connectors,"mock_used":False,"fixture_used":False}}
