def build_thesis_library_brief_md():
 lines=[]
 lines.append("# Thesis Library Brief")
 lines.append("")
 lines.append("## Overview")
 lines.append("- 8 ticker theses registered")
 lines.append("- 1 strengthened (NVDA), 2 supported, 2 observed, 2 context_supported, 1 unconfirmed")
 lines.append("- Confidence: 1 high, 6 medium, 1 low")
 lines.append("")
 lines.append("## Key Thesis Changes")
 lines.append("- NVDA: strengthened via Phase137 execution")
 lines.append("- 688041: unchanged, valuation limitation acknowledged")
 lines.append("- 300394: unchanged, cninfo still blocked")
 lines.append("")
 lines.append("## Risks Visible")
 lines.append("- 688041: derived valuation may differ from market")
 lines.append("- NVDA: AI capex cycle may moderate (low severity)")
 lines.append("- 300394: source data quality limited by cninfo missing")
 lines.append("")
 lines.append("---")
 lines.append("*Research-only thesis library. No trade recommendations.*")
 return "\n".join(lines)
