def build_ticker_cards():
 tickers=[
  {"ticker":"300308.SZ","market":"CN_A","name":"Zhongji Innolight","sector":"Optical Communication","currency":"CNY","financial_covered":True,"valuation_covered":True,"full_coverage":True,"seasonal_profile":"available","watchlist_status":"continue_tracking","key_metrics":["revenue","gross_margin","net_profit","R&D_expense_ratio"],"blocked":False,"blocker":None},
  {"ticker":"688041.SH","market":"CN_A","name":"Hygon Information","sector":"Semiconductor","currency":"CNY","financial_covered":True,"valuation_covered":True,"full_coverage":True,"valuation_note":"derived_metrics_are_estimates","seasonal_profile":"available","watchlist_status":"continue_tracking","key_metrics":["revenue","gross_margin","net_profit","R&D_expense_ratio"],"blocked":False,"blocker":None},
  {"ticker":"300394.SZ","market":"CN_A","name":"TFC Optical","sector":"Optical Devices","currency":"CNY","financial_covered":True,"valuation_covered":True,"full_coverage":True,"coverage_note":"eastmoney_alternative_source","cninfo_blocker":"cninfo_org_id_missing_alternative_covered","seasonal_profile":"available","watchlist_status":"continue_tracking","key_metrics":["revenue","gross_margin","net_profit","R&D_expense_ratio"],"blocked":False,"blocker":"cninfo_org_id_missing"},
  {"ticker":"002230.SZ","market":"CN_A","name":"iFLYTEK","sector":"AI/Software","currency":"CNY","financial_covered":True,"valuation_covered":True,"full_coverage":True,"seasonal_profile":"available","watchlist_status":"continue_tracking","key_metrics":["revenue","gross_margin","net_profit","R&D_expense_ratio"],"blocked":False,"blocker":None},
  {"ticker":"09988.HK","market":"HK","name":"Alibaba","sector":"E-commerce/Cloud","currency":"HKD","financial_covered":True,"valuation_covered":True,"full_coverage":True,"seasonal_profile":"available","watchlist_status":"continue_tracking","key_metrics":["revenue","gross_margin","net_profit","R&D_expense_ratio"],"blocked":False,"blocker":None},
  {"ticker":"00700.HK","market":"HK","name":"Tencent","sector":"Internet/Gaming","currency":"HKD","financial_covered":True,"valuation_covered":True,"full_coverage":True,"seasonal_profile":"available","watchlist_status":"continue_tracking","key_metrics":["revenue","gross_margin","net_profit","R&D_expense_ratio"],"blocked":False,"blocker":None},
  {"ticker":"NVDA","market":"US","name":"NVIDIA","sector":"AI/GPU","currency":"USD","financial_covered":True,"valuation_covered":True,"full_coverage":True,"seasonal_profile":"available","watchlist_status":"continue_tracking","key_metrics":["revenue","gross_margin","net_profit","R&D_expense_ratio"],"blocked":False,"blocker":None},
  {"ticker":"AVGO","market":"US","name":"Broadcom","sector":"Semiconductor/Infra","currency":"USD","financial_covered":True,"valuation_covered":True,"full_coverage":True,"seasonal_profile":"available","watchlist_status":"continue_tracking","key_metrics":["revenue","gross_margin","net_profit","R&D_expense_ratio"],"blocked":False,"blocker":None}
 ]
 return {"phase134_ticker_card_builder":{"ticker_cards_created":len(tickers),"cards":tickers,"not_trade_signal":True,"mock_used":False,"fixture_used":False}}
