def build_brief_md():
 L=[]
 L.append("# Outcome Tracking")
 L.append("")
 L.append("## Status")
 L.append("- Outcome tracking system operational")
 L.append("- Ready to link outcomes to research decisions")
 L.append("- All safety boundaries enforced")
 L.append("")
 L.append("## Outcome Types")
 L.append("- 12 outcome types: evidence confirmed/weakened, catalyst realized/failed, risk materialized/dissolved, signal accurate/noise, source refreshed/stale, deep dive completed, decision reversed")
 L.append("")
 L.append("## Blocked Tickers")
 L.append("- 300394.SZ: CNINFO org_id missing, remains blocked")
 L.append("- 688041.SH: valuation incomplete")
 L.append("")
 L.append("## Safety")
 L.append("- No profit/loss tracking")
 L.append("- No return metrics tracking")
 L.append("- No financial outcome measurement")
 L.append("- Research-only mode enforced")
 L.append("")
 L.append("*No investment recommendations. No financial tracking.*")
 import os as _os
 return _os.linesep.join(L)
