from smr_phase90_config import get_delivery
from datetime import datetime
import json,os
from pathlib import Path

def build_delivery_artifacts():
    cfg=get_delivery();now=datetime.now().strftime("%Y-%m-%d_%H%M%S")
    outbox=Path(cfg["outbox_path"]);outbox.mkdir(parents=True,exist_ok=True)
    artifacts=[]
    # Load unified integration
    try:
        from smr_phase89_integration import build_unified_integration
        data=build_unified_integration()
        d=data["phase89_unified_integration"]
    except:
        d={"tickers_total":8,"full_coverage":0,"partial":0,"blocked":1,"source_health_overall":"degraded","note":"phase89_unavailable"}
    # JSON
    json_path=outbox/f"daily_intelligence_{now}.json"
    with open(json_path,"w",encoding="utf-8") as f:json.dump(d,f,ensure_ascii=False,indent=2)
    artifacts.append({"format":"json","path":str(json_path),"size_bytes":json_path.stat().st_size})
    # Markdown
    md_path=outbox/f"daily_intelligence_{now}.md"
    md=f"# Daily Intelligence Report - {now}\n\n## Summary\n\n- Tickers: {d.get('tickers_total',8)}\n- Full Coverage: {d.get('full_coverage',0)}\n- Partial: {d.get('partial',1)}\n- Blocked: {d.get('blocked',1)}\n- Source Health: {d.get('source_health_overall','N/A')}\n- Known Gaps: {d.get('known_gaps',[])} \n\n## Safety\n\n- Watch-only: true\n- No trade signals\n- No target price\n- No position sizing\n- No pending/order/trade\n\n*Generated by Phase 90 Scheduled Automation*\n"
    with open(md_path,"w",encoding="utf-8") as f:f.write(md)
    artifacts.append({"format":"markdown","path":str(md_path),"size_bytes":md_path.stat().st_size})
    # HTML
    html_path=outbox/f"daily_intelligence_{now}.html"
    html=f"<!DOCTYPE html><html><head><meta charset='utf-8'><title>Daily Intelligence {now}</title><style>body{{font-family:Arial;max-width:800px;margin:auto;padding:20px}}h1{{color:#333}}.summary{{background:#f5f5f5;padding:15px;border-radius:5px}}.warning{{color:#c00}}</style></head><body><h1>Daily Intelligence Report</h1><p>{now}</p><div class='summary'><h2>Summary</h2><ul><li>Tickers: {d.get('tickers_total',8)}</li><li>Full Coverage: {d.get('full_coverage',0)}</li><li>Partial: {d.get('partial',1)}</li><li>Blocked: {d.get('blocked',1)}</li><li>Source Health: {d.get('source_health_overall','N/A')}</li></ul></div><p class='warning'>Watch-only. No trade signals. No target price.</p></body></html>"
    with open(html_path,"w",encoding="utf-8") as f:f.write(html)
    artifacts.append({"format":"html","path":str(html_path),"size_bytes":html_path.stat().st_size})
    # Manifest
    manifest={"delivery_id":now,"timestamp":now,"artifacts":artifacts,"tickers_total":d.get("tickers_total",8),"watch_only":True}
    manifest_path=outbox/f"manifest_{now}.json"
    with open(manifest_path,"w",encoding="utf-8") as f:json.dump(manifest,f,ensure_ascii=False,indent=2)
    # History
    hist_path=Path(cfg["history_path"]);hist_path.parent.mkdir(parents=True,exist_ok=True)
    with open(hist_path,"a",encoding="utf-8") as f:f.write(json.dumps(manifest,ensure_ascii=False)+"\n")
    return {"phase90_delivery_builder":{"delivery_id":now,"outbox_path":str(outbox),"formats_generated":cfg["formats"],"artifacts":artifacts,"manifest":str(manifest_path),"history_appended":True,"history_path":str(hist_path),"history_path_ignored":cfg["gitignored"],"mock_used":False,"fixture_used":False}}
