def build_deep_dive_brief_md():
 lines=[]
 lines.append("# Deep Dive Research Brief")
 lines.append("")
 lines.append("## Active Tasks")
 lines.append("")
 lines.append("### DD-135-001: 688041 Valuation Input Deep Dive [HIGH]")
 lines.append("- Type: valuation_input_review")
 lines.append("- Trigger: Owner deep dive request (FB-OA-001)")
 lines.append("- Questions: 5 research questions defined")
 lines.append("- Evidence: 5 categories, 2 manual confirmations required")
 lines.append("- Sources: cninfo primary, aggregated fallback")
 lines.append("- Cannot conclude: target price, buy/sell recommendation")
 lines.append("")
 lines.append("### DD-136-002: NVDA Financial Quality Review [MEDIUM]")
 lines.append("- Type: financial_quality_review")
 lines.append("- Trigger: Owner confirmed NVDA card useful (FB-TC-001)")
 lines.append("- Questions: 3 research questions defined")
 lines.append("- Cannot conclude: future stock performance, target price")
 lines.append("")
 lines.append("### DD-136-003: 300394 Source Quality Review [LOW]")
 lines.append("- Type: source_quality_review")
 lines.append("- Trigger: Owner flagged eastmoney noise (FB-SS-001)")
 lines.append("- Cannot conclude: cninfo resolution timeline")
 lines.append("")
 lines.append("## Important Limitations")
 lines.append("- All deep dive tasks are research-only")
 lines.append("- Research packets are not investment recommendations")
 lines.append("- Cannot conclude items must be respected")
 lines.append("- Manual confirmations needed where marked")
 lines.append("")
 lines.append("---")
 lines.append("*Research-only deep dive workflow. No trade recommendations, target prices, or position sizing.*")
 return "\n".join(lines)
