from smr_phase87_config import get_industry_directions
def build_external_source_registry():
    sources=[{"source_id":"eastmoney_news_search","source_name":"Eastmoney News Search","source_type":"public_news_page","industry_directions":["ai_optical_module","ai_chip_domestic_compute","cloud_capex_ai_infra","semiconductor_ai_supply_chain"],"signal_types":["industry_news","product_price_supply_demand","policy_export_control_risk"],"markets":["CN_A"],"requires_network":True,"requires_login":False,"allows_final_evidence":True,"reliability_baseline":0.65,"known_limitations":"CN-A shares only; API pagination limited","fallback_priority":1},
    {"source_id":"existing_disclosure_text_pool","source_name":"Phase 73-78 Disclosure Text Pool","source_type":"company_disclosure_reuse","industry_directions":["ai_optical_module","ai_chip_domestic_compute","semiconductor_ai_supply_chain"],"signal_types":["order_contract_tender","product_price_supply_demand","policy_export_control_risk"],"markets":["CN_A"],"requires_network":False,"requires_login":False,"allows_final_evidence":True,"reliability_baseline":0.80,"known_limitations":"Only available for stocks with prior PDF/OCR extraction","fallback_priority":2},
    {"source_id":"yfinance_news","source_name":"Yahoo Finance News","source_type":"public_news_page","industry_directions":["cloud_capex_ai_infra","semiconductor_ai_supply_chain"],"signal_types":["industry_news","capex_demand_proxy"],"markets":["US","HK"],"requires_network":True,"requires_login":False,"allows_final_evidence":True,"reliability_baseline":0.60,"known_limitations":"English-language only","fallback_priority":1},
    {"source_id":"exchange_announcement_cninfo","source_name":"CNINFO / Exchange Announcements","source_type":"exchange_announcement","industry_directions":["ai_optical_module","ai_chip_domestic_compute"],"signal_types":["order_contract_tender","product_price_supply_demand"],"markets":["CN_A"],"requires_network":True,"requires_login":False,"allows_final_evidence":True,"reliability_baseline":0.75,"known_limitations":"Only CN stocks with valid cninfo org_id","fallback_priority":2},
    {"source_id":"company_ir_page_known_url","source_name":"Company IR Known URL Catalog","source_type":"known_url_catalog","industry_directions":["ai_optical_module","ai_chip_domestic_compute","cloud_capex_ai_infra","semiconductor_ai_supply_chain"],"signal_types":["industry_news","order_contract_tender","product_price_supply_demand"],"markets":["CN_A","HK","US"],"requires_network":True,"requires_login":False,"allows_final_evidence":False,"reliability_baseline":0.50,"known_limitations":"Manual curation; URLs may change","fallback_priority":3},
    {"source_id":"government_policy_page","source_name":"Government Policy / Export Control Pages","source_type":"government_policy_page","industry_directions":["ai_chip_domestic_compute","semiconductor_ai_supply_chain"],"signal_types":["policy_export_control_risk"],"markets":["CN_A","US"],"requires_network":True,"requires_login":False,"allows_final_evidence":True,"reliability_baseline":0.70,"known_limitations":"Policy documents are formal but interpretation requires caution","fallback_priority":3},
    {"source_id":"existing_pdf_text_pool","source_name":"Existing Annual/Quarterly Report PDF Text","source_type":"existing_pdf_text_pool","industry_directions":["ai_optical_module","ai_chip_domestic_compute","cloud_capex_ai_infra","semiconductor_ai_supply_chain"],"signal_types":["product_price_supply_demand","policy_export_control_risk","order_contract_tender"],"markets":["CN_A","HK","US"],"requires_network":False,"requires_login":False,"allows_final_evidence":True,"reliability_baseline":0.85,"known_limitations":"Annual reports are lagging; may not capture latest quarter","fallback_priority":2},
    {"source_id":"public_industry_news_rss","source_name":"Public Industry News / RSS","source_type":"public_news_page","industry_directions":["cloud_capex_ai_infra","semiconductor_ai_supply_chain"],"signal_types":["industry_news","capex_demand_proxy"],"markets":["HK","US"],"requires_network":True,"requires_login":False,"allows_final_evidence":True,"reliability_baseline":0.55,"known_limitations":"General news may not be company-specific","fallback_priority":3},
    {"source_id":"curated_keyword_catalog","source_name":"Curated Industry Keyword Catalog","source_type":"known_url_catalog","industry_directions":["ai_optical_module","ai_chip_domestic_compute","cloud_capex_ai_infra","semiconductor_ai_supply_chain"],"signal_types":["industry_news","capex_demand_proxy"],"markets":["CN_A","HK","US"],"requires_network":False,"requires_login":False,"allows_final_evidence":True,"reliability_baseline":0.55,"known_limitations":"Static catalog; requires manual refresh","fallback_priority":4}]
    directions=get_industry_directions()
    return {"phase87_external_source_registry":{"sources_defined":len(sources),"source_types":len(set(s["source_type"] for s in sources)),"directions_covered":len(directions),"rows":sources,"mock_used":False,"fixture_used":False}}
