def build_seasonal_analytics_brief_md():
 L=[]
 L.append("# Seasonal Analytics Dashboard")
 L.append("")
 L.append("## Portfolio Overview (8 tickers, 3 markets)")
 L.append("- CN_A (4): 300308.SZ, 688041.SH, 300394.SZ, 002230.SZ")
 L.append("- HK (2): 09988.HK, 00700.HK")
 L.append("- US (2): NVDA, AVGO")
 L.append("")
 L.append("## Coverage Status: FULL (8/8)")
 L.append("- Financial data: all available")
 L.append("- Valuation data: all available")
 L.append("- Blocked: 0 | Partial: 0")
 L.append("")
 L.append("## Seasonal Panels Available")
 L.append("- Financial Trend: revenue, net profit, gross margin, OCF, R&D ratio")
 L.append("- Valuation Trend: PE, PB, PS, EV/EBITDA")
 L.append("- Cross-market Comparison: CN_A vs HK vs US")
 L.append("- Opportunity/Catalyst: earnings calendar by market")
 L.append("- Watchlist Status: coverage monitoring")
 L.append("- Source Coverage: data source health")
 L.append("- Signal Effectiveness: signal quality tracking")
 L.append("- Gap/Risk: known gaps and risk dimensions")
 L.append("- Owner Action Queue: pending owner tasks")
 L.append("")
 L.append("## Currency Boundary")
 L.append("CNY, HKD, USD tracked separately. No cross-currency direct comparison.")
 L.append("")
 L.append("*Seasonal analytics dashboard v1. Research-only. First snapshot.*")
 import os as _os
 return _os.linesep.join(L)
